spring.application.name=loanassistant

spring.datasource.url=jdbc:mysql://localhost:3306/loanbot
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


server.port=8080
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]

# Startup optimizations
spring.main.lazy-initialization=true
